language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  postgresql: "9.1"

before_install:
  - git submodule update --init --recursive

before_script:
  - export PG='127.0.0.1:5432:tarantool:tarantool:tarantool'
  - export MYSQL='127.0.0.1:3306:tarantool:tarantool:tarantool'

install:
  - sh ./extra/travis/build_$TRAVIS_OS_NAME.sh

script:
  - sh ./extra/travis/test_$TRAVIS_OS_NAME.sh

notifications:
  irc:
    channels:
      - irc.freenode.net#tarantool
    on_success: change
    on_failure: always
  email: false

git:
  depth: 500
